### ISSUE TITLE
CI: smoke test failure in docker compose up

### ISSUE THREAD

**Issue by yokofly** [timeplus-io/proton#393]
**Describe what's wrong**

https://github.com/timeplus-io/proton/actions/runs/7147196986/job/19467073281#step:7:394
https://github.com/timeplus-io/proton/actions/runs/7147196986/job/19467577389#step:7:396
https://github.com/timeplus-io/proton/actions/runs/7146988181/job/19466812153#step:7:402
https://github.com/timeplus-io/proton/actions/runs/7146988163/job/19466818559#step:7:404
**Error message and/or stacktrace**

```
Building wheels for collected packages: dockerpty, docopt
  Building wheel for dockerpty (pyproject.toml): started
  Building wheel for dockerpty (pyproject.toml): finished with status 'done'
  Created wheel for dockerpty: filename=dockerpty-0.4.1-py3-none-any.whl size=16597 sha256=5c8cdb6b0ca75c778d1d0f77d324f8d653db5b451ffd54af52e800d9daf40d94
  Stored in directory: /root/.cache/pip/wheels/18/00/32/f75cd03098074f988a01c59a2e3a55ae9c0773eb66acb4cb5e
  Building wheel for docopt (pyproject.toml): started
  Building wheel for docopt (pyproject.toml): finished with status 'done'
  Created wheel for docopt: filename=docopt-0.6.2-py2.py3-none-any.whl size=13706 sha256=76d1ed94a03bf61ee77974d9bb54d700417830b130a9a7f1c7ecca9ab384da3e
  Stored in directory: /root/.cache/pip/wheels/fc/ab/d4/5da2067ac95b36618c629a5f93f809425700506f72c9732fac
Successfully built dockerpty docopt
Installing collected packages: unidiff, texttable, sseclient-py, pytz, makefun, kafka-python, docopt, urllib3, tzlocal, toml, six, python-dotenv, pyrsistent, pycparser, py, psycopg2-binary, pluggy, packaging, loguru, jmespath, iniconfig, idna, distro, decopatch, charset-normalizer, certifi, bcrypt, attrs, websocket-client, requests, python-dateutil, pytest-cases, pytest, proton-driver, jsonschema, dockerpty, cffi, timeplus, pytest-metadata, pynacl, docker, cryptography, botocore, s3transfer, pytest-html, pyOpenSSL, paramiko, boto3, docker-compose
Successfully installed attrs-23.1.0 bcrypt-4.1.1 boto3-1.20.4 botocore-1.23.54 certifi-2023.11.17 cffi-1.16.0 charset-normalizer-3.3.2 cryptography-39.0.2 decopatch-1.4.10 distro-1.8.0 docker-7.0.0 docker-compose-1.29.2 dockerpty-0.4.1 docopt-0.6.2 idna-3.6 iniconfig-2.0.0 jmespath-0.10.0 jsonschema-3.2.0 kafka-python-2.0.2 loguru-0.7.2 makefun-1.15.2 packaging-23.2 paramiko-3.3.1 pluggy-1.3.0 proton-driver-0.2.10 psycopg2-binary-2.9.3 py-1.11.0 pyOpenSSL-23.0.0 pycparser-2.21 pynacl-1.5.0 pyrsistent-0.20.0 pytest-6.2.5 pytest-cases-3.6.5 pytest-html-3.1.1 pytest-metadata-2.0.4 python-dateutil-2.8.2 python-dotenv-0.21.1 pytz-2023.3.post1 requests-2.31.0 s3transfer-0.5.2 six-1.16.0 sseclient-py-1.8.0 texttable-1.7.0 timeplus-1.1.2 toml-0.10.2 tzlocal-5.2 unidiff-0.7.0 urllib3-1.26.7 websocket-client-0.59.0
2023-12-08 23:54:46,903 [    INFO] [MainProcess] [ci_runner] [<module>] docker compose up... (ci_runner.py:488)
2023-12-08 23:54:46,903 [   DEBUG] [MainProcess] [ci_runner] [<module>] env_docker_compose_res: False (ci_runner.py:489)
Traceback (most recent call last):
  File "/actions-runner/_work/proton/proton/tests/stream/ci_runner.py", line 491, in <module>
ci_runner starting: run_mode = github, loop = 1, logging_level=DEBUG, test_retry = True, test_suite_timeout = 900, test_folders = test_stream_smoke starts
args_dict = {'run_mode': 'github', 'debug': True, 'test_folders': 'test_stream_smoke', 'test_suites': 'None', 'id': 'None', 'loop': 1, 'settings': 'redp,nativelog', 'cluster_query_route_mode': 'None', 'cluster_query_node': 'None', 'create_stream_shards': 'None', 'create_stream_replicas': 'None', 'no_retry': False, 'test_suite_timeout': 900, 'tmp': 'None'}
    raise Exception("Env docker compose up failure.")
Exception: Env docker compose up failure.
self._event.value = {'event_type': 'test_event', 'payload': {'detailed_type': 'status', 'details': 'start'}}
self._tag_value = {'version': '0.1', 'repo_name': 'proton', 'test_info': {'test_id': '2a6c0e00-9625-11ee-b524-9113bba36471', 'test_name': 'ci_runner', 'test_type': 'ci_smoke'}, 'build_info': {'build_type': 'release_build', 'pr_number': 'develop', 'commit_sha': '2bd0eddb3b8735d018bbf73c21c27b8718902e12'}, 'run_time_info': {'os': 'Linux', 'platform': 'X64'}}
test_event_start sent
Error: Process completed with exit code 1.
```
**Additional context**

**Comment by yokofly** [comment]
```
# python3 ci_runner.py --debug --settings=redp,nativelog
ci_runner starting: run_mode = github, loop = 1, logging_level=DEBUG, test_retry = True, test_suite_timeout = 900, test_folders = test_stream_smoke starts
args_dict = {'run_mode': 'github', 'debug': True, 'test_folders': 'test_stream_smoke', 'test_suites': 'None', 'id': 'None', 'loop': 1, 'settings': 'redp,nativelog', 'cluster_query_route_mode': 'None', 'cluster_query_node': 'None', 'create_stream_shards': 'None', 'create_stream_replicas': 'None', 'no_retry': False, 'test_suite_timeout': 900, 'tmp': 'None'}
self._event.value = {'event_type': 'test_event', 'payload': {'detailed_type': 'status', 'details': 'start'}}
self._tag_value = {'version': '0.1', 'repo_name': 'proton', 'test_info': {'test_id': '96a78e48-9650-11ee-8927-bbdd7bf617c7', 'test_name': 'ci_runner', 'test_type': 'ci_smoke'}, 'build_info': {'build_type': 'release_build', 'pr_number': '0', 'commit_sha': '0'}, 'run_time_info': {'os': 'Linux', 'platform': 'x86_64'}}
test_event_start sent
compose_up: Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "/usr/local/lib/python3.10/dist-packages/compose/cli/docker_client.py", line 124, in docker_client
    kwargs = kwargs_from_env(environment=environment, ssl_version=tls_version)
TypeError: kwargs_from_env() got an unexpected keyword argument 'ssl_version'

2023-12-09 05:05:36,976 [    INFO] [MainProcess] [ci_runner] [<module>] docker compose up... (ci_runner.py:488)
2023-12-09 05:05:36,976 [   DEBUG] [MainProcess] [ci_runner] [<module>] env_docker_compose_res: False (ci_runner.py:489)
Traceback (most recent call last):
  File "/home/ubuntu/proton/tests/stream/ci_runner.py", line 491, in <module>
    raise Exception("Env docker compose up failure.")
Exception: Env docker compose up failure.
root@ip-172-31-17-253:/home/ubuntu/proton/tests/stream# pip list| grep docker
docker                 7.0.0
docker-compose         1.29.2
dockerpty              0.4.1

```
